[package]
name = "sdf-dead-reckoning"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[features]
piston_image = [ "image" ]

[dependencies]
# TODO let users of this library specify if they want to use intrinsics?
half = "1.3.0" # { version = "1.3.0", features = [ "use-intrinsics" ] }
image = { version = "0.21.0", optional = true }

[[example]]
name = "write_png"
required-features = ["piston_image" ]
